services:
  - type: web
    name: finance-diary-api
    env: node
    plan: free
    buildCommand: npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        value: mongodb+srv://vighnesh:admin@cluster.mongodb.net/finance_diary
      - key: JWT_SECRET
        generateValue: true
      - key: FRONTEND_URL
        value: https://your-actual-vercel-app-url.vercel.app